name: radio_browser
description: A Flutter take-home project for browsing and playing internet radio stations.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  audio_session: ^0.2.3
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  just_audio: ^0.10.5
  sensors_plus: ^7.0.0
  record: ^6.2.0
  path_provider: ^2.1.5
  just_audio_background: ^0.0.1-beta.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  flutter_lints: ^5.0.0
  mocktail: ^1.0.5
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/offline_radio.PNG
    - assets/illustrations/favorites_empty.PNG
    - assets/illustrations/bot_radio.PNG
    - assets/illustrations/no_results.PNG
    - assets/illustrations/app_icon.png
    - assets/illustrations/splash_screen.png
